/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.BitCoinMall;



import Business.BitCoinMall.Product;
import Business.BitCoinMall.ProductCatalog;
import Business.Enterprise.MallEnterprise;
import Business.Role.Producer;
import java.awt.CardLayout;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JIN
 */
public class ManageProductCatalogJPanel extends javax.swing.JPanel {
   

    private JPanel upc;
    private MallEnterprise mallenterprise;
//    private Product product;
    private ProductCatalog productcatalog;


    public ManageProductCatalogJPanel(JPanel upc,MallEnterprise mallenterprise,ProductCatalog productcatalog) {

        initComponents();        
        this.upc = upc; 
        this.mallenterprise = mallenterprise;
//        this.product = product;
        this.productcatalog = productcatalog;
        populateTable();


    }

    /**
     * Creates new form ManageAccountJPanel
     */
    
    
     public ImageIcon ResizeIamge(String imagepath,byte[] pic)
    {
        ImageIcon myImage = null;
        
        if(imagepath != null)
        {
            myImage = new  ImageIcon(imagepath);
        }
            else{
                    myImage = new ImageIcon(pic);
                    }
        
        Image img = myImage.getImage();
        Image img2 = img.getScaledInstance(lbl_showimage.getWidth(), lbl_showimage.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(img2);
        return image;    
    }
     

      private void displayImage(Product product)
    {
        if(product==null) return;
        if(product.getPicture()==null) return;
        if(product.getPicture().trim().isEmpty()) return;
        String path = product.getPicture();  
        lbl_showimage.setIcon(ResizeIamge(path, null));
    }

    
public void populateTable(){
        DefaultTableModel dtm = (DefaultTableModel)tblProductCatalog.getModel();
        dtm.setRowCount(0);

        for(Product p : mallenterprise.getProductCatalog().getProductCatalog()){
            Object[] row = new Object[4];
            row[0] =p;
            row[1] =p.getId();
            row[2] =p.getPrise();
            row[3] =p.getAvail();

            dtm.addRow(row);
        
        //lbl_showimage.setIcon(ResizeIamge(path, null));
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProductCatalog = new javax.swing.JTable();
        btnFile = new javax.swing.JButton();
        lbl_showimage = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        create = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(900, 600));

        jLabel2.setFont(new java.awt.Font("新細明體", 0, 24)); // NOI18N
        jLabel2.setText("Manage Product Catalog");

        tblProductCatalog.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product", "Model Number", "Price", "Availibility"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProductCatalog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductCatalogMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblProductCatalog);
        if (tblProductCatalog.getColumnModel().getColumnCount() > 0) {
            tblProductCatalog.getColumnModel().getColumn(0).setResizable(false);
            tblProductCatalog.getColumnModel().getColumn(1).setResizable(false);
            tblProductCatalog.getColumnModel().getColumn(2).setResizable(false);
            tblProductCatalog.getColumnModel().getColumn(3).setResizable(false);
        }

        btnFile.setBackground(new java.awt.Color(255, 255, 255));
        btnFile.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/BitCoinMall/picture/upload_file.png"))); // NOI18N
        btnFile.setText("UploadFromFile");
        btnFile.setIconTextGap(10);
        btnFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFileActionPerformed(evt);
            }
        });

        lbl_showimage.setBackground(new java.awt.Color(255, 255, 204));
        lbl_showimage.setOpaque(true);

        back.setBackground(new java.awt.Color(255, 255, 255));
        back.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/BitCoinMall/picture/back.png"))); // NOI18N
        back.setText("Back");
        back.setIconTextGap(22);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        create.setBackground(new java.awt.Color(255, 255, 255));
        create.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        create.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/BitCoinMall/picture/Adds.png"))); // NOI18N
        create.setText("Create");
        create.setIconTextGap(25);
        create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createActionPerformed(evt);
            }
        });

        delete.setBackground(new java.awt.Color(255, 255, 255));
        delete.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/BitCoinMall/picture/Minus.png"))); // NOI18N
        delete.setText("Delete");
        delete.setIconTextGap(25);
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(255, 255, 255));
        btnUpdate.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/BitCoinMall/picture/update.png"))); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.setIconTextGap(25);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(back)
                        .addGap(81, 81, 81)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 758, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(create)
                                .addGap(61, 61, 61)
                                .addComponent(btnUpdate)
                                .addGap(63, 63, 63)
                                .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnFile)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_showimage, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(back))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_showimage, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFile, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(create)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delete))
                .addContainerGap(244, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFileActionPerformed
        ProductCatalog pc = mallenterprise.getProductCatalog();
        pc.uploadProduct();
        populateTable();
    }//GEN-LAST:event_btnFileActionPerformed

    private void tblProductCatalogMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductCatalogMouseClicked
        int selectedrow = tblProductCatalog.getSelectedRow();
        if(selectedrow<0) return;
        Product p = (Product) tblProductCatalog.getValueAt(selectedrow, 0);
        displayImage(p);
    }//GEN-LAST:event_tblProductCatalogMouseClicked

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        upc.remove(this);   
        CardLayout layout = (CardLayout) upc.getLayout();
        layout.previous(upc); 
    }//GEN-LAST:event_backActionPerformed

    private void createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createActionPerformed
        // TODO add your handling code here:
        CreateNewProductJPanel panel = new CreateNewProductJPanel(upc,mallenterprise,this); 
        upc.add("CreateNewProductJPanel", panel);
        CardLayout layout = (CardLayout) upc.getLayout();
        layout.next(upc);
    }//GEN-LAST:event_createActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed

        
        
        int selectedrow = tblProductCatalog.getSelectedRow();

        if(selectedrow >=0){
            Product p = (Product)tblProductCatalog.getValueAt(selectedrow, 0);
            UpdateProductJPanel panel = new UpdateProductJPanel(upc, p, this); 
            upc.add("UpdateProductJPanel", panel);
            CardLayout layout = (CardLayout) upc.getLayout();
            layout.next(upc); 
        }
        else{
            JOptionPane.showMessageDialog(null, "Please select any row", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        int selectedrow = tblProductCatalog.getSelectedRow();

        if(selectedrow >=0){
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(null, "Delete selected row?", "Warning", dialogButton);
            if(dialogResult == JOptionPane.YES_OPTION){
                Product p = (Product)tblProductCatalog.getValueAt(selectedrow, 0);
                mallenterprise.getProductCatalog().deleteProduct(p);
                JOptionPane.showMessageDialog(null, "Delete successfully");
                populateTable();
            }            
        }
        else{
            JOptionPane.showMessageDialog(null, "Please select any row", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_deleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton btnFile;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton create;
    private javax.swing.JButton delete;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_showimage;
    private javax.swing.JTable tblProductCatalog;
    // End of variables declaration//GEN-END:variables
}
