/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.BitCoinMall;





import Business.BitCoinMall.Product;
import Business.BitCoinMall.ProductCatalog;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.MallEnterprise;
import Business.Organization.AccountingOrg;
import Business.Organization.InventoryOrg;
import Business.Role.Producer;
import Business.UserAccount.UserAccount;
import UserInterface.InvestmentEnterprise.ViewAccountJPanel;
import UserInterface.ShortMessage.ShortMessageJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;
/**
 *
 * @author JIN
 */
public class ProducerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdminWorkAreaJPanel
     */
    private JPanel upc;
    private UserAccount account;
    private InventoryOrg inventoryOrg;
 
    private MallEnterprise mallEnterprise;
    private EcoSystem ecoSystem;
//    private Product product;
    private ProductCatalog productcatalog;

    public ProducerWorkAreaJPanel(JPanel upc, UserAccount account, InventoryOrg inventoryOrg, Enterprise enterprise, EcoSystem ecoSystem) {
        initComponents();
        setSize(800,600);
        this.account = account;
        this.upc =upc;
        this.inventoryOrg = inventoryOrg;
        this.mallEnterprise = (MallEnterprise) enterprise;
        this.ecoSystem = ecoSystem;
        this.productcatalog = mallEnterprise.getProductCatalog();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        btnManageProduct = new javax.swing.JButton();
        lbl_show_thephoto = new javax.swing.JLabel();
        btnMOrderCatalog = new javax.swing.JButton();
        AccountInfoBtn = new javax.swing.JButton();
        AccountInfoBtn1 = new javax.swing.JButton();

        jLabel4.setFont(new java.awt.Font("新細明體", 0, 24)); // NOI18N
        jLabel4.setText("Producer Work Area");

        btnManageProduct.setText("Manage Product Catalog");
        btnManageProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageProductActionPerformed(evt);
            }
        });

        lbl_show_thephoto.setBackground(new java.awt.Color(255, 255, 204));
        lbl_show_thephoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/producer.png"))); // NOI18N
        lbl_show_thephoto.setOpaque(true);

        btnMOrderCatalog.setText("Master Order Catalog");
        btnMOrderCatalog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMOrderCatalogActionPerformed(evt);
            }
        });

        AccountInfoBtn.setText("View Account");
        AccountInfoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccountInfoBtnActionPerformed(evt);
            }
        });

        AccountInfoBtn1.setText("InMail");
        AccountInfoBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccountInfoBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(AccountInfoBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMOrderCatalog, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnManageProduct, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AccountInfoBtn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 231, Short.MAX_VALUE)
                        .addComponent(lbl_show_thephoto)
                        .addGap(125, 125, 125))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(btnManageProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnMOrderCatalog, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(AccountInfoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(AccountInfoBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(lbl_show_thephoto)))
                .addContainerGap(236, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageProductActionPerformed
        ManageProductCatalogJPanel mpcjp = new ManageProductCatalogJPanel(upc,mallEnterprise,productcatalog);
        upc.add("ManageProductCatalogJPanel", mpcjp);
        CardLayout cardLayout = (CardLayout) upc.getLayout();
        cardLayout.next(upc);        // TODO add your handling code here:
    }//GEN-LAST:event_btnManageProductActionPerformed

    private void btnMOrderCatalogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMOrderCatalogActionPerformed
        ViewProducerOrderHistoryJPanel vpohjp = new ViewProducerOrderHistoryJPanel(upc, inventoryOrg);
        upc.add("ViewProducerOrderHistoryJPanel", vpohjp);
        CardLayout cardLayout = (CardLayout) upc.getLayout();
        cardLayout.next(upc);
    }//GEN-LAST:event_btnMOrderCatalogActionPerformed

    private void AccountInfoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccountInfoBtnActionPerformed
        ViewAccountJPanel smjp = new ViewAccountJPanel(upc,mallEnterprise , ecoSystem);
        upc.add("ViewAccountJPanel", smjp);
        CardLayout layout = (CardLayout) upc.getLayout();
        layout.next(upc); 
    }//GEN-LAST:event_AccountInfoBtnActionPerformed

    private void AccountInfoBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccountInfoBtn1ActionPerformed
        ShortMessageJPanel smjp = new ShortMessageJPanel(upc, account, ecoSystem);
        upc.add("ShortMessageJPanel_SysAdmin", smjp);
        CardLayout layout = (CardLayout) upc.getLayout();
        layout.next(upc);        // TODO add your handling code here:
    }//GEN-LAST:event_AccountInfoBtn1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AccountInfoBtn;
    private javax.swing.JButton AccountInfoBtn1;
    private javax.swing.JButton btnMOrderCatalog;
    private javax.swing.JButton btnManageProduct;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lbl_show_thephoto;
    // End of variables declaration//GEN-END:variables
}
