/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Retailer;

import Business.Business;
import Business.Retailer;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Chung-Yang Li
 */
public class ManageRetailerJPanel extends javax.swing.JPanel {
   
    private JPanel CardSequenceJPanel; 
    private Business business;
    public ManageRetailerJPanel(JPanel CardSequenceJPanel, Business business) {
        initComponents();        
        this.CardSequenceJPanel = CardSequenceJPanel; 
        this.business = business;                    
        populateTable();
    }

    /**
     * Creates new form ManageAccountJPanel
     */

    public void populateTable(){
        DefaultTableModel dtm = (DefaultTableModel)tblRetailer.getModel();
        dtm.setRowCount(0);

        for(Retailer r : business.getRd().getRetailerDirectory()){
            Object[] row = new Object[2];
            row[0] = r;
            row[1] = r.getLocation();

     
            dtm.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDelete = new javax.swing.JButton();
        btnMngProductCatalog = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        txtAccountNum = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblRetailer = new javax.swing.JTable();
        btnCreateAirliner = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(900, 600));

        btnDelete.setFont(new java.awt.Font("新細明體", 0, 18)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnMngProductCatalog.setFont(new java.awt.Font("新細明體", 0, 18)); // NOI18N
        btnMngProductCatalog.setText("Manage Product");
        btnMngProductCatalog.setPreferredSize(new java.awt.Dimension(79, 31));
        btnMngProductCatalog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMngProductCatalogActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("新細明體", 0, 24)); // NOI18N
        jLabel2.setText("Manage Retailer");

        btnSearch.setFont(new java.awt.Font("新細明體", 0, 18)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.setEnabled(false);
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        tblRetailer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Retailer", "Location"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblRetailer);
        if (tblRetailer.getColumnModel().getColumnCount() > 0) {
            tblRetailer.getColumnModel().getColumn(0).setResizable(false);
            tblRetailer.getColumnModel().getColumn(1).setResizable(false);
        }

        btnCreateAirliner.setFont(new java.awt.Font("新細明體", 0, 18)); // NOI18N
        btnCreateAirliner.setText("Create");
        btnCreateAirliner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAirlinerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(337, 337, 337)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtAccountNum, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCreateAirliner, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMngProductCatalog, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(172, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCreateAirliner, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMngProductCatalog, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAccountNum, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, Short.MAX_VALUE))
                .addGap(330, 330, 330))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnMngProductCatalogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMngProductCatalogActionPerformed
        int selectedrow = tblRetailer.getSelectedRow();

        if(selectedrow >=0){
            Retailer a = (Retailer)tblRetailer.getValueAt(selectedrow, 0);
            ManageProductCatalogJPanel panel = new ManageProductCatalogJPanel(CardSequenceJPanel, a, this);
            CardSequenceJPanel.add("ManageAirlinerJPanel", panel);
            CardLayout layout = (CardLayout) CardSequenceJPanel.getLayout();
            layout.next(CardSequenceJPanel);
        }
        else{
            JOptionPane.showMessageDialog(null, "Please select any row", "Warning", JOptionPane.WARNING_MESSAGE);
        }   // TODO add your handling code here:
    }//GEN-LAST:event_btnMngProductCatalogActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int selectedrow = tblRetailer.getSelectedRow();

        if(selectedrow >=0){
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(null, "Delete selected row?", "Warning", dialogButton);
            if(dialogResult == JOptionPane.YES_OPTION){
                Retailer r = (Retailer)tblRetailer.getValueAt(selectedrow, 0);
                business.getRd().deleteRetailer(r);
                JOptionPane.showMessageDialog(null, "Delete successfully");  
                populateTable();
            }            
        }
        else{
            JOptionPane.showMessageDialog(null, "Please select any row", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnCreateAirlinerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAirlinerActionPerformed
        CreateRetailerJPanel panel = new CreateRetailerJPanel(CardSequenceJPanel, business, this); 
        CardSequenceJPanel.add("CreateAirlinerJPanel", panel);
        CardLayout layout = (CardLayout) CardSequenceJPanel.getLayout();
        layout.next(CardSequenceJPanel);
    }//GEN-LAST:event_btnCreateAirlinerActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        //        Retailer result = ad.searchAirliner(txtAccountNum.getText());
        //        if(result == null){
            //            JOptionPane.showMessageDialog(null, "Account number doesn't exist", "Information", JOptionPane.INFORMATION_MESSAGE);
            //        }
        //        else{
            //            ViewAccountJPanel panel = new ViewAccountJPanel(CardSequenceJPanel, result, this);
            //            CardSequenceJPanel.add("ViewAccountJPanel", panel);
            //            CardLayout layout = (CardLayout) CardSequenceJPanel.getLayout();
            //            layout.next(CardSequenceJPanel);
            //        }
        //        txtAccountNum.setText("");
    }//GEN-LAST:event_btnSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateAirliner;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnMngProductCatalog;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblRetailer;
    private javax.swing.JTextField txtAccountNum;
    // End of variables declaration//GEN-END:variables
}
