/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import UserInterface.Airliners.AirlinersMngWorkAreaJPanel;
import Business.AirlinerDirectory;
import Business.FlightSchedule;
import java.awt.CardLayout;

/**
 *
 * @author Chung-Yang Li
 */
public class TravelAgencyMain extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    private AirlinerDirectory ad;
    private FlightSchedule fs;
    public TravelAgencyMain() {
        initComponents();
        this. ad = new AirlinerDirectory();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        CardSequenceJPanel = new javax.swing.JPanel();
        topPanel = new javax.swing.JPanel();
        btnTravelAgency = new javax.swing.JButton();
        btnAirlinerManager = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        splitPane.setDividerLocation(100);
        splitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        CardSequenceJPanel.setPreferredSize(new java.awt.Dimension(900, 600));
        CardSequenceJPanel.setLayout(new java.awt.CardLayout());
        splitPane.setRightComponent(CardSequenceJPanel);

        topPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTravelAgency.setFont(new java.awt.Font("新細明體", 0, 18)); // NOI18N
        btnTravelAgency.setText("Travel Agency Manager");
        btnTravelAgency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTravelAgencyActionPerformed(evt);
            }
        });
        topPanel.add(btnTravelAgency, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, 210, 50));

        btnAirlinerManager.setFont(new java.awt.Font("新細明體", 0, 18)); // NOI18N
        btnAirlinerManager.setText("Airliner Manager");
        btnAirlinerManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAirlinerManagerActionPerformed(evt);
            }
        });
        topPanel.add(btnAirlinerManager, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 30, 160, 50));

        splitPane.setLeftComponent(topPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTravelAgencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTravelAgencyActionPerformed
        TravelAgencyMngWorkAreaJPanel panel = new TravelAgencyMngWorkAreaJPanel(CardSequenceJPanel, ad); 
        CardSequenceJPanel.add("AirlinertMngWorkAreaJPanel", panel);
        CardLayout layout = (CardLayout) CardSequenceJPanel.getLayout();
        layout.next(CardSequenceJPanel);
    }//GEN-LAST:event_btnTravelAgencyActionPerformed

    private void btnAirlinerManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAirlinerManagerActionPerformed
        AirlinersMngWorkAreaJPanel panel = new AirlinersMngWorkAreaJPanel(CardSequenceJPanel, ad); 
        CardSequenceJPanel.add("AirlinersMngWorkAreaJPanel", panel);
        CardLayout layout = (CardLayout) CardSequenceJPanel.getLayout();
        layout.next(CardSequenceJPanel);        // TODO add your handling code here:
    }//GEN-LAST:event_btnAirlinerManagerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TravelAgencyMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TravelAgencyMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TravelAgencyMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TravelAgencyMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TravelAgencyMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CardSequenceJPanel;
    private javax.swing.JButton btnAirlinerManager;
    private javax.swing.JButton btnTravelAgency;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables
}
