/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ShortMessage;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Role.Role;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.ShortMessage;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lingfengzhou
 */
public class ShortMessageJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ShortMessageJPanel
     */
    private EcoSystem ecoSystem;
    private UserAccount userAccount;
    private JPanel userProcessContainer;

    public ShortMessageJPanel(JPanel userProcessContainer, UserAccount account, EcoSystem ecoSystem) {
        initComponents();
        setSize(800, 600);
        this.ecoSystem = ecoSystem;
        this.userAccount = account;
        this.userProcessContainer = userProcessContainer;
        populateEnterpriseComboBox();
//        popChatArea();
        popUnreadMsgTab();      
    }

    public void populateEnterpriseComboBox() {
        EntComboBox.removeAllItems();
        for (Enterprise e : ecoSystem.getEnterpriseNetwork().getEnterpriseList()) {
            EntComboBox.addItem(e);
            populateOrgComboBox(e);
        }

    }

    public void populateOrgComboBox(Enterprise enterprise) {
        orgComboBox.removeAllItems();
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
            orgComboBox.addItem(organization);
            populateRoleComboBox(organization);
        }
    }

    public void populateRoleComboBox(Organization organization) {
        roleComboBox.removeAllItems();
        for (Role role : organization.getSupportedRole()) {
            roleComboBox.addItem(role);
            popContactList(role, organization);
        }
    }

    public void popContactList(Role role, Organization org) {
        
        DefaultListModel dlm = new DefaultListModel();
        dlm.removeAllElements();
        for (UserAccount u : org.getUserAccountDirectory().getUserAccountList()) {
//            if (u.getRole().equals(role) && !u.equals(userAccount)) {
            if (u.getRole().toString().equals(role.toString()) && !u.equals(userAccount)) {
                dlm.addElement(u);
            }
        }
        jListContact.setModel(dlm);

    }
    
    public void popUnreadcontact(UserAccount unreadAccount){
        
        DefaultListModel dlm = new DefaultListModel();
        dlm.removeAllElements();
        dlm.addElement(unreadAccount);
        jListContact.setModel(dlm);
        
    }

    public void popChatArea() {
        UserAccount revAccount = (UserAccount) jListContact.getSelectedValue();
        chatTxtArea.setText("");
        for (ShortMessage s : userAccount.getMessageQueue().getMessageList()) {
            if (s.getReceiver().equals(revAccount) || s.getSender().equals(revAccount)) {
                if(s.getSender().equals(revAccount))s.setStatus("Read");
                chatTxtArea.setText(chatTxtArea.getText().trim() + "\n" +s.getSender().toString() +": "+s.getMessage() + " [" + s.getRequestDate()+"] ");
            }
        }
        popUnreadMsgTab();

    }
    
    public void popUnreadMsgTab(){
        
        DefaultTableModel dtm = (DefaultTableModel) msgTab.getModel();
        dtm.setRowCount(0);
        List<ShortMessage> res = userAccount.getMessageQueue().searchUnreadMessage(userAccount);
        for(ShortMessage s:res){
            Object[] row = new Object[2];
            row[0] = s.getSender();
            row[1] = s;
            dtm.addRow(row);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jButtonBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListContact = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        orgComboBox = new javax.swing.JComboBox();
        roleComboBox = new javax.swing.JComboBox();
        EntComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        mesJTextField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        chatTxtArea = new javax.swing.JTextArea();
        sendBtn = new javax.swing.JButton();
        BCTBtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        msgTab = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jSplitPane1.setDividerLocation(300);

        jButtonBack.setBackground(new java.awt.Color(255, 255, 255));
        jButtonBack.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/BitCoinMall/picture/back.png"))); // NOI18N
        jButtonBack.setText("Back");
        jButtonBack.setIconTextGap(22);
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        jListContact.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jListContact.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Contact 1", "Contact 2", "Contact 3", "Contact 4", "Contact 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jListContact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListContactMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jListContact);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("Contacts");

        orgComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orgComboBoxActionPerformed(evt);
            }
        });

        roleComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roleComboBoxActionPerformed(evt);
            }
        });

        EntComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntComboBoxActionPerformed(evt);
            }
        });

        jLabel2.setText("Enterprise:");

        jLabel3.setText("Organization:");

        jLabel4.setText("Role:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                        .addGap(124, 124, 124))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonBack)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(roleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(orgComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EntComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonBack)
                .addGap(9, 9, 9)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EntComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(orgComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(99, 99, 99)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(382, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        mesJTextField.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N

        chatTxtArea.setColumns(20);
        chatTxtArea.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        chatTxtArea.setRows(5);
        jScrollPane2.setViewportView(chatTxtArea);

        sendBtn.setBackground(new java.awt.Color(255, 255, 255));
        sendBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        sendBtn.setForeground(new java.awt.Color(51, 255, 0));
        sendBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/BitCoinMall/picture/next.png"))); // NOI18N
        sendBtn.setText("Send");
        sendBtn.setIconTextGap(10);
        sendBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendBtnActionPerformed(evt);
            }
        });

        BCTBtn.setBackground(new java.awt.Color(255, 255, 255));
        BCTBtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BCTBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/BitCoinMall/picture/broadcast.png"))); // NOI18N
        BCTBtn.setText("Broadcast");
        BCTBtn.setIconTextGap(10);
        BCTBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCTBtnActionPerformed(evt);
            }
        });

        msgTab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "From", "Msg"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        msgTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                msgTabMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(msgTab);

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel5.setText("Short Messages:");

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel6.setText("New Messages:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane2)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(mesJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(BCTBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(sendBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addGap(298, 298, 298))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mesJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sendBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BCTBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(391, Short.MAX_VALUE))
        );

        jSplitPane1.setRightComponent(jPanel2);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void orgComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orgComboBoxActionPerformed
        Organization organization = (Organization) orgComboBox.getSelectedItem();
        if (organization != null) {
            populateRoleComboBox(organization);
        }
    }//GEN-LAST:event_orgComboBoxActionPerformed

    private void roleComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roleComboBoxActionPerformed
        Role role = (Role) roleComboBox.getSelectedItem();
        Organization organization = (Organization) orgComboBox.getSelectedItem();
        if (role != null && organization != null) {
            popContactList(role, organization);
        }
    }//GEN-LAST:event_roleComboBoxActionPerformed

    private void EntComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntComboBoxActionPerformed
        Enterprise enterprise = (Enterprise) EntComboBox.getSelectedItem();
        if (enterprise != null) {
            populateOrgComboBox(enterprise);
        }
    }//GEN-LAST:event_EntComboBoxActionPerformed

    private void sendBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendBtnActionPerformed
        UserAccount revAccount = (UserAccount) jListContact.getSelectedValue();
        String mes = mesJTextField.getText();
        if (mes.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Empty message is not allowed", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        ShortMessage sm = revAccount.getMessageQueue().addSendMessage(userAccount, revAccount, mes);
        userAccount.getMessageQueue().addMessage(sm);
        popChatArea();
        mesJTextField.setText("");
        
    }//GEN-LAST:event_sendBtnActionPerformed

    private void BCTBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCTBtnActionPerformed
        String bcm = mesJTextField.getText();
        StringBuilder sb = new StringBuilder(bcm);
        sb.append(" (Broadcasting)");
        String mes = sb.toString();
        if (mes.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Empty message is not allowed", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
//        List<UserAccount> revAccounts = new ArrayList<>();
        for(Enterprise e:ecoSystem.getEnterpriseNetwork().getEnterpriseList()){
            for(Organization o: e.getOrganizationDirectory().getOrganizationList()){
                for(UserAccount u:o.getUserAccountDirectory().getUserAccountList()){
                    if(!u.equals(userAccount)){
                        ShortMessage sm = u.getMessageQueue().addSendMessage(userAccount, u, mes);
                        userAccount.getMessageQueue().addMessage(sm);
//                        revAccounts.add(u);
                    }
                }
            }
        }
//        userAccount.getMessageQueue().addBroadcastMessage(userAccount, revAccounts, mes);
        popChatArea();
        mesJTextField.setText("");
    }//GEN-LAST:event_BCTBtnActionPerformed

    private void jListContactMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListContactMouseClicked
        popChatArea();
    }//GEN-LAST:event_jListContactMouseClicked

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void msgTabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_msgTabMouseClicked
        int selectedrow = msgTab.getSelectedRow();
        if(selectedrow<0) return;
        UserAccount unreadAccount = (UserAccount) msgTab.getValueAt(selectedrow, 0);
        popUnreadcontact(unreadAccount);
    }//GEN-LAST:event_msgTabMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BCTBtn;
    private javax.swing.JComboBox EntComboBox;
    private javax.swing.JTextArea chatTxtArea;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList jListContact;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField mesJTextField;
    private javax.swing.JTable msgTab;
    private javax.swing.JComboBox orgComboBox;
    private javax.swing.JComboBox roleComboBox;
    private javax.swing.JButton sendBtn;
    // End of variables declaration//GEN-END:variables
}
