/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SystemMantenanceEnterprise;

import Business.EcoSystem;
import Business.Enterprise.DepositEnterprise;
import Business.Enterprise.Enterprise;
import Business.Enterprise.Enterprise.Type;
import Business.Organization.Organization;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTree;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author lingfengzhou
 */
public class ManageEnterpriseNetworkJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageEnterpriseNetworkJPanel
     */
    private EcoSystem ecoSystem;
    private JPanel userProcessContainer;
    public ManageEnterpriseNetworkJPanel(JPanel userProcessContainer, EcoSystem ecoSystem) {
        initComponents();
        setSize(800,600);
        this.ecoSystem = ecoSystem;
        this.userProcessContainer = userProcessContainer;
        populateEnterpriseTree();
        populateTypeCombobox();
        setBackground(new java.awt.Color(204, 255, 255));
        
    }
    
    public void populateEnterpriseTree(){
        DefaultTreeModel dtm = (DefaultTreeModel) EcoJTree.getModel();
        dtm.setRoot(null);
        DefaultMutableTreeNode top = new DefaultMutableTreeNode(ecoSystem);
        for(Enterprise e: ecoSystem.getEnterpriseNetwork().getEnterpriseList()){
            DefaultMutableTreeNode son = new DefaultMutableTreeNode(e);
            top.add(son);
            for(Organization o: e.getOrganizationDirectory().getOrganizationList()){
                DefaultMutableTreeNode grandson = new DefaultMutableTreeNode(o);
                son.add(grandson);
            }
        }
        dtm.setRoot(top);
    }
    
    public void populateTypeCombobox(){
        typejComboBox.removeAllItems();
        for(Enterprise.Type type:Enterprise.Type.values()){
            if(!type.equals(Enterprise.Type.SystemMantenanceEnterprise)&&!type.equals(Enterprise.Type.DepositEnterprise)){
                typejComboBox.addItem(type);
            }
        }
        
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        EcoJTree = new javax.swing.JTree();
        jLabel4 = new javax.swing.JLabel();
        lblFname3 = new javax.swing.JLabel();
        txtEnterpriseName = new javax.swing.JTextField();
        lblFname4 = new javax.swing.JLabel();
        typejComboBox = new javax.swing.JComboBox();
        createEnterpriseBtn = new javax.swing.JButton();
        back = new javax.swing.JButton();

        EcoJTree.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jScrollPane1.setViewportView(EcoJTree);

        jLabel4.setFont(new java.awt.Font("新細明體", 0, 24)); // NOI18N
        jLabel4.setText("Manage Enterpise Network");

        lblFname3.setFont(new java.awt.Font("新細明體", 0, 18)); // NOI18N
        lblFname3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFname3.setText("Enterprise name:");

        txtEnterpriseName.setFont(new java.awt.Font("新細明體", 0, 14)); // NOI18N

        lblFname4.setFont(new java.awt.Font("新細明體", 0, 18)); // NOI18N
        lblFname4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFname4.setText("Type:");

        typejComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        createEnterpriseBtn.setBackground(new java.awt.Color(255, 255, 255));
        createEnterpriseBtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        createEnterpriseBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/BitCoinMall/picture/Adds.png"))); // NOI18N
        createEnterpriseBtn.setText("Create Enterprise");
        createEnterpriseBtn.setIconTextGap(10);
        createEnterpriseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createEnterpriseBtnActionPerformed(evt);
            }
        });

        back.setBackground(new java.awt.Color(255, 255, 255));
        back.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/BitCoinMall/picture/back.png"))); // NOI18N
        back.setText("Back");
        back.setIconTextGap(22);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblFname3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtEnterpriseName, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblFname4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(typejComboBox, 0, 184, Short.MAX_VALUE)
                                    .addComponent(createEnterpriseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(back))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEnterpriseName, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFname3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFname4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(typejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addComponent(createEnterpriseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(150, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createEnterpriseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createEnterpriseBtnActionPerformed
        
        String eName = txtEnterpriseName.getText();
        Type type = (Type) typejComboBox.getSelectedItem();
        if(eName.isEmpty()||type == null) {
            JOptionPane.showMessageDialog(null, "Please enter the reqiured info","Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
        Enterprise enterprise = ecoSystem.getEnterpriseNetwork().addEnterprise(type, eName);
        // When create a new Enterprise, a admin org and financialAccount will be created as well
        DepositEnterprise.getInstance().getFinancialAccountDirectory().addFinancialAccount(eName);
        Organization AdminOrg = enterprise.getOrganizationDirectory().addOrganization(Organization.Type.Admin);
        JOptionPane.showMessageDialog(null, "New EnterPrise Created");
        populateEnterpriseTree();
        
    }//GEN-LAST:event_createEnterpriseBtnActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
         userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree EcoJTree;
    private javax.swing.JButton back;
    private javax.swing.JButton createEnterpriseBtn;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFname3;
    private javax.swing.JLabel lblFname4;
    private javax.swing.JTextField txtEnterpriseName;
    private javax.swing.JComboBox typejComboBox;
    // End of variables declaration//GEN-END:variables
}
