/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SystemMantenanceEnterprise;

import Business.BitCoinMall.Product;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.AdminOrg;
import Business.UserAccount.UserAccount;
import UserInterface.ShortMessage.ShortMessageJPanel;
import java.awt.CardLayout;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author lingfengzhou
 */
public class SystemAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SystemAdminWorkAreaJPanel
     */
    private EcoSystem ecoSystem;
    private UserAccount userAccount;
    private JPanel userProcessContainer;
    public SystemAdminWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, AdminOrg adminOrg, Enterprise enterprise, EcoSystem ecoSystem){
        initComponents();
        setSize(800,600);
        this.ecoSystem = ecoSystem;
        this.userAccount = account;
        this.userProcessContainer  = userProcessContainer;
    }

//     public ImageIcon ResizeIamge(String imagepath,byte[] pic)
//    {
//        ImageIcon myImage = null;
//        
//        if(imagepath != null)
//        {
//            myImage = new  ImageIcon(imagepath);
//        }
//            else{
//                    myImage = new ImageIcon(pic);
//                    }
//        
//        Image img = myImage.getImage();
//        Image img2 = img.getScaledInstance(lbl_showimage.getWidth(), lbl_showimage.getHeight(), Image.SCALE_SMOOTH);
//        ImageIcon image = new ImageIcon(img2);
//        return image;    
//    }
//     
//       private void displayImage(Product product)
//    {
//        if(product==null) return;
//        if(product.getPicture()==null) return;
//        if(product.getPicture().trim().isEmpty()) return;
//        String path = product.getPicture();  
//        lbl_showimage.setIcon(ResizeIamge(path, null));
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        btnManageEmployee = new javax.swing.JButton();
        btnAnalysis = new javax.swing.JButton();
        btnManageEnterpriseNetwork = new javax.swing.JButton();
        InMail = new javax.swing.JButton();
        lbl_show_thephoto = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 255));

        jLabel4.setFont(new java.awt.Font("新細明體", 0, 24)); // NOI18N
        jLabel4.setText("Admin Work Area");

        btnManageEmployee.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnManageEmployee.setText("Manage Enterprise Admin");
        btnManageEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageEmployeeActionPerformed(evt);
            }
        });

        btnAnalysis.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnAnalysis.setText("Analysis");
        btnAnalysis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalysisActionPerformed(evt);
            }
        });

        btnManageEnterpriseNetwork.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnManageEnterpriseNetwork.setText("Enterprise Network");
        btnManageEnterpriseNetwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageEnterpriseNetworkActionPerformed(evt);
            }
        });

        InMail.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        InMail.setText("InMail");
        InMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InMailActionPerformed(evt);
            }
        });

        lbl_show_thephoto.setBackground(new java.awt.Color(255, 255, 204));
        lbl_show_thephoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/SUPER ADMIN.png"))); // NOI18N
        lbl_show_thephoto.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnManageEnterpriseNetwork, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAnalysis, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnManageEmployee, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(InMail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(158, 158, 158)
                .addComponent(lbl_show_thephoto)
                .addContainerGap(201, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnManageEnterpriseNetwork, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnManageEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(InMail, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAnalysis, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(lbl_show_thephoto, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(305, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageEmployeeActionPerformed
                ManageAdminJPanel majp = new ManageAdminJPanel(userProcessContainer, ecoSystem);
                userProcessContainer.add("ManageAdminJPanel", majp);
                CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
                cardLayout.next(userProcessContainer);        
    }//GEN-LAST:event_btnManageEmployeeActionPerformed

    private void btnAnalysisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalysisActionPerformed
        AnalysisJPanel mejp = new AnalysisJPanel(userProcessContainer, ecoSystem);
        userProcessContainer.add("AnalysisJPanel",mejp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnAnalysisActionPerformed

    private void btnManageEnterpriseNetworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageEnterpriseNetworkActionPerformed
        ManageEnterpriseNetworkJPanel mejp = new ManageEnterpriseNetworkJPanel(userProcessContainer,ecoSystem);
        userProcessContainer.add("ManageEcosystemJPanel",mejp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageEnterpriseNetworkActionPerformed

    private void InMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InMailActionPerformed
        ShortMessageJPanel smjp = new ShortMessageJPanel(userProcessContainer, userAccount, ecoSystem);
        userProcessContainer.add("ShortMessageJPanel_SysAdmin", smjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_InMailActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton InMail;
    private javax.swing.JButton btnAnalysis;
    private javax.swing.JButton btnManageEmployee;
    private javax.swing.JButton btnManageEnterpriseNetwork;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lbl_show_thephoto;
    // End of variables declaration//GEN-END:variables
}
